"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import {
  ArrowRight,
  Clapperboard,
  Heart,
  Maximize2,
  Pause,
  Play,
  RotateCcw,
  Volume2,
  VolumeX,
} from "lucide-react";
import { chefImg, LOCAL, PEXELS, dishImg, wideImg } from "@/lib/images";

/* ————————————————— storyboard ————————————————— */

type Move = "in" | "out" | "left" | "right";
type Scene = {
  src: string;
  tag: string;
  hindi: string;
  roman: string;
  move: Move;
  /** Devanagari voice-over line, read aloud in sync with the subtitle */
  speech: string;
};

const SCENES: Scene[] = [
  {
    src: LOCAL.heroMaa,
    tag: "chapter 01 — ghar",
    hindi: "दूर शहर। दूर घर।",
    roman: "par bhookh hamesha maa-wali hoti hai",
    speech: "दूर शहर। दूर घर। लेकिन भूख — हमेशा माँ वाली।",
    move: "in",
  },
  {
    src: chefImg(PEXELS.chefRekha),
    tag: "chapter 02 — maas",
    hindi: "यहाँ हर रसोई में एक माँ बैठी है",
    roman: "6 sheher · 120+ verified home chefs",
    speech:
      "माँज़ मैजिक में, हर रसोई में एक माँ बैठी है। छह शहर, एक सौ बीस से ज़्यादा शानदार होम शेफ़।",
    move: "right",
  },
  {
    src: chefImg(PEXELS.chefFatima),
    tag: "chapter 03 — haath",
    hindi: "हर डब्बा ऐसे बंद होता है जैसे अपने बच्चे का हो",
    roman: "maa-grade hygiene, maa-grade pyaar",
    speech: "हर डब्बा ऐसे बंद होता है… जैसे अपने बच्चे का हो।",
    move: "left",
  },
  {
    src: dishImg(PEXELS.gharwaliThali),
    tag: "chapter 04 — tazgi",
    hindi: "सुबह 5 बजे — सिर्फ़ आज बना खाना",
    roman: "no preserved kal, no shortcuts",
    speech:
      "सुबह पाँच बजे से शुरू — सिर्फ़ आज बना ख़ाना। कोई प्रिज़र्वेटिव नहीं, कोई शॉर्टकट नहीं।",
    move: "in",
  },
  {
    src: dishImg(PEXELS.masalaDosa),
    tag: "chapter 05 — swad",
    hindi: "पहली बाइट में पूरी ज़िंदगी लौट आती है",
    roman: "crispy, garam, bilkul amma jaisa",
    speech: "पहली बाइट में — पूरी ज़िंदगी लौट आती है।",
    move: "out",
  },
  {
    src: LOCAL.adStudent,
    tag: "chapter 06 — baccha",
    hindi: "और कहीं एक हॉस्टल रूम में…",
    roman: "woh phone uthata hai — “maa, kha liya”",
    speech: "और फिर कहीं, एक हॉस्टल रूम में… डब्बा खुलता है।",
    move: "in",
  },
];

const END_LINE =
  "माँज़ मैजिक — हर बाइट में माँ का प्यार। घर से दूर अपनों के लिए, आज ही ऑर्डर करो।";

/** Warm Hindi / Indian-English narrator voice, if the browser offers one. */
function pickNarrator(): SpeechSynthesisVoice | null {
  if (typeof window === "undefined" || !("speechSynthesis" in window)) return null;
  const voices = window.speechSynthesis.getVoices();
  return (
    voices.find((v) => /^hi([-_]IN)?/i.test(v.lang)) ??
    voices.find((v) => /en[-_]IN/i.test(v.lang)) ??
    voices.find((v) => /india|hindi|हिन्दी/i.test(v.name)) ??
    null
  );
}

const SCENE_MS = 4300;
const ENDCARD_MS = 4200;
const TOTAL_MS = SCENES.length * SCENE_MS + ENDCARD_MS;
const DURATION_LABEL = "0:30";

/* ————————————————— ambient score (web audio) ————————————————— */
/**
 * A gentle, Indian-flavoured ambient bed synthesized live:
 * tanpura-style drone + soft plucked pentatonic melody with echo.
 * Zero audio files — everything is generated by the browser.
 */

const PENTA = [146.83, 196.0, 220.0, 293.66, 329.63, 392.0, 440.0]; // D pentatonic-ish
const PHRASE = [4, 3, 2, 0, 2, 3, 5, 4, 3, 2, 1, 2];

type AudioParts = { ctx: AudioContext; master: GainNode; timer: number };

function buildAudio(): AudioParts | null {
  try {
    const AC =
      window.AudioContext ??
      (window as unknown as { webkitAudioContext?: typeof AudioContext })
        .webkitAudioContext;
    if (!AC) return null;
    const ctx = new AC();
    const master = ctx.createGain();
    master.gain.value = 0;
    master.connect(ctx.destination);

    // tanpura-style drone
    const droneFilter = ctx.createBiquadFilter();
    droneFilter.type = "lowpass";
    droneFilter.frequency.value = 420;
    droneFilter.connect(master);
    [73.42, 110, 146.83, 220].forEach((freq, i) => {
      const osc = ctx.createOscillator();
      osc.type = "sine";
      osc.frequency.value = freq;
      const g = ctx.createGain();
      g.gain.value = i === 0 ? 0.05 : 0.036;
      // slow breathing LFO
      const lfo = ctx.createOscillator();
      lfo.frequency.value = 0.06 + i * 0.035;
      const lfoGain = ctx.createGain();
      lfoGain.gain.value = 0.012;
      lfo.connect(lfoGain);
      lfoGain.connect(g.gain);
      osc.connect(g);
      g.connect(droneFilter);
      osc.start();
      lfo.start();
    });

    // echo chamber for the melody
    const delay = ctx.createDelay(1.2);
    delay.delayTime.value = 0.42;
    const feedback = ctx.createGain();
    feedback.gain.value = 0.38;
    const wet = ctx.createGain();
    wet.gain.value = 0.4;
    delay.connect(feedback);
    feedback.connect(delay);
    delay.connect(wet);
    wet.connect(master);

    let phraseIndex = 0;
    const pluck = () => {
      const base = PENTA[PHRASE[phraseIndex % PHRASE.length]];
      phraseIndex += 1;
      const shimmer = phraseIndex % 6 === 0;
      [base, ...(shimmer ? [base * 2] : [])].forEach((freq, k) => {
        const osc = ctx.createOscillator();
        osc.type = "sine";
        osc.frequency.value = freq;
        const g = ctx.createGain();
        const t = ctx.currentTime;
        const peak = k === 0 ? 0.06 : 0.02;
        g.gain.setValueAtTime(0, t);
        g.gain.linearRampToValueAtTime(peak, t + 0.02);
        g.gain.exponentialRampToValueAtTime(0.0001, t + 2.6);
        osc.connect(g);
        g.connect(master);
        g.connect(delay);
        osc.start(t);
        osc.stop(t + 2.8);
      });
    };
    pluck();
    const timer = window.setInterval(pluck, 1600);

    return { ctx, master, timer };
  } catch {
    return null;
  }
}

function formatTime(ms: number) {
  const total = Math.max(0, Math.round(ms / 1000));
  const m = Math.floor(total / 60);
  const s = total % 60;
  return `${m}:${s.toString().padStart(2, "0")}`;
}

/* ————————————————— component ————————————————— */

export function AdFilm() {
  const containerRef = useRef<HTMLDivElement>(null);
  const audioRef = useRef<AudioParts | null>(null);
  const [started, setStarted] = useState(false);
  const [playing, setPlaying] = useState(false);
  const [muted, setMuted] = useState(false);
  const [ended, setEnded] = useState(false);
  const [elapsed, setElapsed] = useState(0);

  const step = Math.min(Math.floor(elapsed / SCENE_MS), SCENES.length);
  const isEndCard = step >= SCENES.length;
  const pct = Math.min(100, (elapsed / TOTAL_MS) * 100);

  const fadeAudio = useCallback((target: number, seconds = 0.5) => {
    const parts = audioRef.current;
    if (!parts) return;
    const { ctx, master } = parts;
    master.gain.cancelScheduledValues(ctx.currentTime);
    master.gain.setValueAtTime(master.gain.value, ctx.currentTime);
    master.gain.linearRampToValueAtTime(target, ctx.currentTime + seconds);
  }, []);

  /* ————— voice-over engine ————— */
  const playingRef = useRef(false);
  playingRef.current = playing;
  const mutedRef = useRef(false);
  mutedRef.current = muted;
  const spokenRef = useRef("");

  const speak = useCallback(
    (text: string, key: string) => {
      if (typeof window === "undefined" || !("speechSynthesis" in window)) return;
      if (mutedRef.current || spokenRef.current === key) return;
      spokenRef.current = key;
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      const voice = pickNarrator();
      if (voice) utterance.voice = voice;
      utterance.lang = voice?.lang ?? "hi-IN";
      utterance.rate = 1.05; // ad-film energy
      utterance.pitch = 1.08;
      utterance.volume = 1;
      // duck the music under the narrator, like a real commercial
      utterance.onstart = () => fadeAudio(0.28, 0.3);
      utterance.onend = () => {
        if (playingRef.current && !mutedRef.current) fadeAudio(0.9, 0.5);
      };
      window.speechSynthesis.speak(utterance);
    },
    [fadeAudio]
  );

  const start = useCallback(() => {
    setStarted(true);
    setEnded(false);
    spokenRef.current = "";
    window.speechSynthesis?.getVoices(); // warm the voice list
    if (!audioRef.current) audioRef.current = buildAudio();
    audioRef.current?.ctx.resume().catch(() => {});
    setPlaying(true);
  }, []);

  // playback ticker
  useEffect(() => {
    if (!playing) return;
    const id = window.setInterval(() => {
      setElapsed((e) => Math.min(e + 100, TOTAL_MS));
    }, 100);
    return () => window.clearInterval(id);
  }, [playing]);

  // audio follows play state
  useEffect(() => {
    if (!started) return;
    fadeAudio(playing && !muted ? 0.9 : 0, 0.6);
  }, [playing, muted, started, fadeAudio]);

  // narrator reads the subtitle of each chapter
  useEffect(() => {
    if (!started || !playing || muted) return;
    const key = isEndCard ? "endcard" : `scene-${step}`;
    speak(isEndCard ? END_LINE : SCENES[step].speech, key);
  }, [step, isEndCard, playing, muted, started, speak]);

  // pause / resume the narrator with the film
  useEffect(() => {
    if (typeof window === "undefined" || !("speechSynthesis" in window) || !started)
      return;
    if (playing && !muted) {
      window.speechSynthesis.resume();
    } else {
      window.speechSynthesis.pause();
      if (muted) window.speechSynthesis.cancel();
    }
  }, [playing, muted, started]);

  // finished?
  useEffect(() => {
    if (elapsed >= TOTAL_MS && playing) {
      setPlaying(false);
      setEnded(true);
      if ("speechSynthesis" in window) window.speechSynthesis.cancel();
    }
  }, [elapsed, playing]);

  // cleanup on unmount
  useEffect(() => {
    return () => {
      if ("speechSynthesis" in window) window.speechSynthesis.cancel();
      if (audioRef.current) {
        window.clearInterval(audioRef.current.timer);
        audioRef.current.ctx.close().catch(() => {});
        audioRef.current = null;
      }
    };
  }, []);

  function togglePlay() {
    if (ended) {
      replay();
      return;
    }
    setPlaying((p) => !p);
  }

  function replay() {
    spokenRef.current = "";
    setElapsed(0);
    setEnded(false);
    setPlaying(true);
  }

  function toggleMute() {
    setMuted((m) => !m);
  }

  function seek(e: React.MouseEvent<HTMLDivElement>) {
    const rect = e.currentTarget.getBoundingClientRect();
    const ratio = Math.min(1, Math.max(0, (e.clientX - rect.left) / rect.width));
    setElapsed(ratio * TOTAL_MS);
    setEnded(false);
    if (!playing) setPlaying(true);
  }

  async function goFullscreen() {
    const el = containerRef.current;
    if (!el) return;
    if (document.fullscreenElement) await document.exitFullscreen();
    else await el.requestFullscreen().catch(() => {});
  }

  return (
    <section className="relative overflow-hidden bg-ink-950 py-20 text-cream-100 sm:py-28">
      <div
        aria-hidden
        className="pointer-events-none absolute left-1/2 top-0 size-[560px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-flame-600/15 blur-3xl"
      />
      <div className="mx-auto max-w-5xl px-5 sm:px-8">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-80px" }}
          transition={{ duration: 0.7 }}
          className="text-center"
        >
          <p className="inline-flex items-center gap-2 rounded-full border border-cream-100/15 bg-cream-50/5 px-4 py-2 text-[11px] font-black uppercase tracking-[0.25em] text-marigold-300">
            <Clapperboard size={13} />
            Humara ad film — AI se bana, dil se
          </p>
          <h2 className="mt-4 font-display text-4xl font-black leading-tight tracking-tight text-cream-50 sm:text-6xl">
            30 second mein,{" "}
            <span className="italic text-marigold-300">poora ghar.</span>
          </h2>
          <p className="mx-auto mt-3 max-w-xl font-hindi text-lg italic text-cream-300/80">
            आँखें थोड़ी भर आएँगी — फिर हाथ अपने आप ऑर्डर बटन तक पहुँचेगा
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 36, scale: 0.97 }}
          whileInView={{ opacity: 1, y: 0, scale: 1 }}
          viewport={{ once: true, margin: "-80px" }}
          transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
          className="mt-10"
        >
          <div
            ref={containerRef}
            className="group relative aspect-video overflow-hidden rounded-[28px] border border-cream-100/10 bg-ink-900 shadow-warm sm:rounded-[36px]"
          >
            {!started ? (
              /* ————— poster / play state ————— */
              <button
                onClick={start}
                aria-label="Ad film play karo"
                className="absolute inset-0 size-full text-left"
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={chefImg(PEXELS.chefRekha)}
                  alt="Maa apni rasoi mein paratha sekte hue — Maa's Magic ad film"
                  className="absolute inset-0 size-full object-cover transition-transform duration-[1.4s] ease-out group-hover:scale-[1.05]"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-ink-950/85 via-ink-950/25 to-ink-950/40" />

                {/* cinema bars */}
                <span className="absolute inset-x-0 top-0 h-[7%] bg-ink-950" />
                <span className="absolute inset-x-0 bottom-0 h-[7%] bg-ink-950" />

                {/* pulsing play */}
                <span className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2">
                  <span className="absolute inset-0 -m-3 animate-ping rounded-full bg-flame-500/40" />
                  <span className="absolute inset-0 -m-6 animate-ping rounded-full border border-cream-50/30 [animation-delay:0.4s]" />
                  <span className="relative grid size-20 place-items-center rounded-full bg-flame-500 text-cream-50 shadow-flame transition-transform duration-300 group-hover:scale-110 sm:size-24">
                    <Play size={34} fill="currentColor" className="ml-1.5" />
                  </span>
                </span>

                <span className="absolute bottom-[10%] left-5 flex items-center gap-2 rounded-full bg-ink-950/70 px-4 py-2 text-xs font-bold text-cream-100 backdrop-blur-sm sm:left-8">
                  <Clapperboard size={13} className="text-marigold-300" />
                  Maa&apos;s Magic — Ek AI Kahani Film
                </span>
                <span className="absolute bottom-[10%] right-5 rounded-full bg-ink-950/70 px-4 py-2 text-xs font-bold text-cream-100 backdrop-blur-sm sm:right-8">
                  {DURATION_LABEL} · sound on rakho
                </span>
              </button>
            ) : (
              /* ————— playing state ————— */
              <>
                <div className="absolute inset-0" onClick={togglePlay} role="presentation">
                  <AnimatePresence>
                    {!isEndCard ? (
                      <motion.div
                        key={step}
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        transition={{ duration: 0.9, ease: "easeInOut" }}
                        className="absolute inset-0"
                      >
                        <motion.img
                          src={SCENES[step].src}
                          alt={SCENES[step].tag}
                          initial={
                            SCENES[step].move === "in"
                              ? { scale: 1.24 }
                              : SCENES[step].move === "out"
                                ? { scale: 1 }
                                : SCENES[step].move === "left"
                                  ? { scale: 1.15, x: "3.5%" }
                                  : { scale: 1.15, x: "-3.5%" }
                          }
                          animate={
                            SCENES[step].move === "in"
                              ? { scale: 1 }
                              : SCENES[step].move === "out"
                                ? { scale: 1.24 }
                                : SCENES[step].move === "left"
                                  ? { scale: 1.15, x: "-3.5%" }
                                  : { scale: 1.15, x: "3.5%" }
                          }
                          transition={{
                            duration: SCENE_MS / 1000 + 1,
                            ease: "linear",
                          }}
                          className="absolute inset-0 size-full object-cover"
                        />
                        <div className="absolute inset-0 bg-gradient-to-t from-ink-950/70 via-transparent to-ink-950/25" />
                      </motion.div>
                    ) : (
                      /* ————— brand end card ————— */
                      <motion.div
                        key="endcard"
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        transition={{ duration: 0.9 }}
                        className="absolute inset-0 grid place-items-center overflow-hidden"
                      >
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img
                          src={LOCAL.adPoster}
                          alt=""
                          className="absolute inset-0 size-full scale-110 object-cover opacity-25 blur-[2px]"
                        />
                        <div className="absolute inset-0 bg-ink-950/55" />
                        <div className="relative px-6 text-center">
                          <motion.p
                            initial={{ opacity: 0, y: 14 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: 0.3, duration: 0.6 }}
                            className="text-[10px] font-black uppercase tracking-[0.35em] text-marigold-300"
                          >
                            Maa&apos;s Magic · ghar se door bachon ke liye
                          </motion.p>
                          <motion.p
                            initial={{ opacity: 0, y: 18 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: 0.55, duration: 0.7 }}
                            className="mt-3 font-hindi text-3xl italic leading-snug text-cream-50 sm:text-5xl"
                          >
                            &ldquo;हर बाइट में माँ का प्यार&rdquo;
                          </motion.p>
                          <motion.div
                            initial={{ opacity: 0, y: 18 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: 0.85, duration: 0.6 }}
                            onClick={(e) => e.stopPropagation()}
                            className="mt-6 flex items-center justify-center gap-3"
                          >
                            <Link
                              href="/menu"
                              className="group inline-flex items-center gap-2 rounded-full bg-flame-500 px-6 py-3 text-sm font-bold text-cream-50 shadow-flame transition hover:bg-flame-600 sm:text-base"
                            >
                              Aaj ka khana order karo
                              <ArrowRight
                                size={16}
                                className="transition-transform group-hover:translate-x-1"
                              />
                            </Link>
                            <span className="hidden items-center gap-1.5 text-sm font-semibold text-cream-200/80 sm:inline-flex">
                              <Heart size={13} className="text-flame-400" fill="currentColor" />
                              thank you, maa
                            </span>
                          </motion.div>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>

                  {/* movie captions */}
                  {!isEndCard && (
                    <AnimatePresence mode="wait">
                      <motion.div
                        key={`caption-${step}`}
                        initial={{ opacity: 0, y: 26 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -14 }}
                        transition={{ duration: 0.55, ease: [0.22, 1, 0.36, 1] }}
                        className="pointer-events-none absolute inset-x-0 bottom-[12%] flex justify-center px-6"
                      >
                        <div className="max-w-full rounded-2xl bg-ink-950/45 px-6 py-3 text-center backdrop-blur-[3px]">
                          <p className="font-mono text-[10px] font-bold uppercase tracking-[0.3em] text-marigold-300">
                            {SCENES[step].tag}
                          </p>
                          <p className="mt-1.5 font-hindi text-2xl italic leading-snug text-cream-50 [text-shadow:0_2px_18px_rgba(0,0,0,0.55)] sm:text-4xl">
                            {SCENES[step].hindi}
                          </p>
                          <p className="mt-1 text-xs font-semibold text-cream-200/85 [text-shadow:0_1px_10px_rgba(0,0,0,0.6)] sm:text-sm">
                            {SCENES[step].roman}
                          </p>
                        </div>
                      </motion.div>
                    </AnimatePresence>
                  )}

                  {/* letterbox bars during playback */}
                  <span className="pointer-events-none absolute inset-x-0 top-0 h-[7%] bg-ink-950" />
                  <span
                    className={`pointer-events-none absolute inset-x-0 bottom-0 bg-ink-950 transition-opacity ${isEndCard ? "h-[7%] opacity-0" : "h-[7%] opacity-100"}`}
                  />

                  {/* scene counter */}
                  <span className="pointer-events-none absolute right-5 top-[10%] font-mono text-[10px] font-bold tracking-[0.25em] text-cream-200/80">
                    {isEndCard ? "FIN" : `SC 0${step + 1} / 06`}
                  </span>
                </div>

                {/* controls */}
                <div className="absolute inset-x-0 bottom-0 z-10 bg-gradient-to-t from-ink-950/85 to-transparent px-4 pb-3.5 pt-12 sm:px-6 sm:pb-4">
                  <div className="flex items-center gap-3 sm:gap-4">
                    <button
                      onClick={togglePlay}
                      aria-label={playing ? "Pause" : "Play"}
                      className="grid size-10 shrink-0 place-items-center rounded-full bg-cream-50/15 text-cream-50 backdrop-blur-md transition hover:bg-flame-500"
                    >
                      {playing ? (
                        <Pause size={17} fill="currentColor" />
                      ) : ended ? (
                        <RotateCcw size={16} />
                      ) : (
                        <Play size={17} fill="currentColor" className="ml-0.5" />
                      )}
                    </button>
                    <div
                      onClick={seek}
                      className="group/bar relative h-6 flex-1 cursor-pointer"
                    >
                      <div className="absolute top-1/2 h-1.5 w-full -translate-y-1/2 rounded-full bg-cream-50/20">
                        <div
                          className="relative h-full rounded-full bg-gradient-to-r from-flame-400 to-marigold-300 transition-[width] duration-100"
                          style={{ width: `${pct}%` }}
                        >
                          <span className="absolute -right-1.5 top-1/2 size-3.5 -translate-y-1/2 rounded-full bg-marigold-300 opacity-0 shadow-md transition-opacity group-hover/bar:opacity-100" />
                        </div>
                      </div>
                    </div>
                    <span className="shrink-0 font-mono text-[11px] font-bold text-cream-200/90 sm:text-xs">
                      {formatTime(elapsed)} / {DURATION_LABEL}
                    </span>
                    <button
                      onClick={toggleMute}
                      aria-label={muted ? "Sound on" : "Mute"}
                      className="grid size-10 shrink-0 place-items-center rounded-full bg-cream-50/15 text-cream-50 backdrop-blur-md transition hover:bg-flame-500"
                    >
                      {muted ? <VolumeX size={16} /> : <Volume2 size={16} />}
                    </button>
                    <button
                      onClick={goFullscreen}
                      aria-label="Fullscreen"
                      className="hidden size-10 shrink-0 place-items-center rounded-full bg-cream-50/15 text-cream-50 backdrop-blur-md transition hover:bg-flame-500 sm:grid"
                    >
                      <Maximize2 size={15} />
                    </button>
                  </div>
                </div>
              </>
            )}
          </div>
          <p className="mt-4 text-center text-xs italic text-cream-300/50">
            *har frame AI se bana — lekin jazbaat 100% asli. sound on rakhna —
            maa ki rasoi sunai bhi deti hai.
          </p>
        </motion.div>
      </div>
    </section>
  );
}
